### ISSUE TITLE
stacstac 0.4.0 should have minimum dask dependency of 2022.01.1

### ISSUE THREAD

**Issue by DManowitz** [conda-forge/stackstac-feedstock#18]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

stackstac 0.4.0 currently has a minimum dask version of 2021.4.1.  However stackstac/to_dask.py imports ArraySliceDep, which does not show up until dask 2022.01.1.  Thus, this should be the minimum version of dask for stacstac 0.4.0.

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by TomAugspurger** [comment]
Can you make a PR bumping the requirements to match https://github.com/gjoseph92/stackstac/blob/main/pyproject.toml?

**Comment by DManowitz** [comment]
Sorry, but I'm not actually sure which file to modify for this.

**Comment by gjoseph92** [comment]
@DManowitz this was already addressed in https://github.com/conda-forge/stackstac-feedstock/pull/15/commits/e2aac9d84e8f2ed86b578b29742a7320c72c5060 for v0.4.1. You can see that the dask requirement is already for 2022.1.1: https://github.com/conda-forge/stackstac-feedstock/blob/66915fa97378450b299574f126745583c6fcf47a/recipe/meta.yaml#L25

If you install a newer version of stackstac, you'll get the correct dask dependency.

**Comment by DManowitz** [comment]
The problem is that I don't have an acceptable version of dask installed, so I can't install newer versions, and I wanted to raise this issue for anyone else who might have an earlier version of dask who might get this installed mistakenly and then get errors when trying to use it.
